import { cfgNode, type CfgTree } from "./cfg-runtime";

export const cfgWeapons = {
  "arifle": {
    "ak12": cfgNode("arifle_AK12_F", {
      "arid": "arifle_AK12_arid_F",
      "gl_arid": "arifle_AK12_GL_arid_F",
      "gl": "arifle_AK12_GL_F",
      "gl_lush_arco_pointer": "arifle_AK12_GL_lush_arco_pointer_F",
      "gl_lush_arco_snds_pointer": "arifle_AK12_GL_lush_arco_snds_pointer_F",
      "gl_lush": "arifle_AK12_GL_lush_F",
      "gl_lush_holo_pointer": "arifle_AK12_GL_lush_holo_pointer_F",
      "gl_lush_holo_snds_pointer": "arifle_AK12_GL_lush_holo_snds_pointer_F",
      "lush_arco_pointer": "arifle_AK12_lush_arco_pointer_F",
      "lush_arco_snds_pointer_bipod": "arifle_AK12_lush_arco_snds_pointer_bipod_F",
      "lush_arco_snds_pointer": "arifle_AK12_lush_arco_snds_pointer_F",
      "lush": "arifle_AK12_lush_F",
      "lush_snds_pointer": "arifle_AK12_lush_snds_pointer_F",
    }),
    "ak12u": cfgNode("arifle_AK12U_F", {
      "arid": "arifle_AK12U_arid_F",
      "lush": "arifle_AK12U_lush_F",
      "lush_holo": "arifle_AK12U_lush_holo_F",
      "lush_holo_fl": "arifle_AK12U_lush_holo_fl_F",
      "lush_holo_pointer": "arifle_AK12U_lush_holo_pointer_F",
      "lush_holo_snds_pointer": "arifle_AK12U_lush_holo_snds_pointer_F",
      "lush_snds_pointer": "arifle_AK12U_lush_snds_pointer_F",
    }),
    "akm": cfgNode("arifle_AKM_F", {
      "fl": "arifle_AKM_FL_F",
    }),
    "aks": cfgNode("arifle_AKS_F", {}),
    "arx": {
      "blk": "arifle_ARX_blk_F",
      "ghex_aco_pointer_snds": "arifle_ARX_ghex_ACO_Pointer_Snds_F",
      "ghex_arco_pointer_snds": "arifle_ARX_ghex_ARCO_Pointer_Snds_F",
      "ghex_dms_pointer_snds_bipod": "arifle_ARX_ghex_DMS_Pointer_Snds_Bipod_F",
      "ghex": "arifle_ARX_ghex_F",
      "hex_aco_pointer_snds": "arifle_ARX_hex_ACO_Pointer_Snds_F",
      "hex_arco_pointer_snds": "arifle_ARX_hex_ARCO_Pointer_Snds_F",
      "hex_dms_pointer_snds_bipod": "arifle_ARX_hex_DMS_Pointer_Snds_Bipod_F",
      "hex": "arifle_ARX_hex_F",
      "viper": "arifle_ARX_Viper_F",
      "viper_hex": "arifle_ARX_Viper_hex_F",
    },
    "ctar": {
      "blk_aco": "arifle_CTAR_blk_ACO_F",
      "blk_aco_flash": "arifle_CTAR_blk_aco_flash_F",
      "blk_aco_pointer": "arifle_CTAR_blk_ACO_Pointer_F",
      "blk_aco_pointer_snds": "arifle_CTAR_blk_ACO_Pointer_Snds_F",
      "blk_arco": "arifle_CTAR_blk_ARCO_F",
      "blk_arco_flash": "arifle_CTAR_blk_arco_flash_F",
      "blk_arco_pointer": "arifle_CTAR_blk_ARCO_Pointer_F",
      "blk_arco_pointer_snds": "arifle_CTAR_blk_ARCO_Pointer_Snds_F",
      "blk": "arifle_CTAR_blk_F",
      "blk_flash": "arifle_CTAR_blk_flash_F",
      "blk_pointer": "arifle_CTAR_blk_Pointer_F",
      "ghex": "arifle_CTAR_ghex_F",
      "gl_blk_aco": "arifle_CTAR_GL_blk_ACO_F",
      "gl_blk_aco_flash": "arifle_CTAR_GL_blk_aco_flash_F",
      "gl_blk_aco_pointer_snds": "arifle_CTAR_GL_blk_ACO_Pointer_Snds_F",
      "gl_blk_arco_flash": "arifle_CTAR_GL_blk_arco_flash_F",
      "gl_blk_arco_pointer": "arifle_CTAR_GL_blk_ARCO_Pointer_F",
      "gl_blk": "arifle_CTAR_GL_blk_F",
      "gl_ghex": "arifle_CTAR_GL_ghex_F",
      "gl_hex": "arifle_CTAR_GL_hex_F",
      "hex": "arifle_CTAR_hex_F",
    },
    "ctars": {
      "blk": "arifle_CTARS_blk_F",
      "blk_flash": "arifle_CTARS_blk_flash_F",
      "blk_pointer": "arifle_CTARS_blk_Pointer_F",
      "ghex": "arifle_CTARS_ghex_F",
      "hex": "arifle_CTARS_hex_F",
    },
    "katiba": cfgNode("arifle_Katiba_F", {
      "aco": "arifle_Katiba_ACO_F",
      "aco_pointer": "arifle_Katiba_ACO_pointer_F",
      "aco_pointer_snds": "arifle_Katiba_ACO_pointer_snds_F",
      "arco": "arifle_Katiba_ARCO_F",
      "arco_pointer": "arifle_Katiba_ARCO_pointer_F",
      "arco_pointer_snds": "arifle_Katiba_ARCO_pointer_snds_F",
      "c_aco": "arifle_Katiba_C_ACO_F",
      "c_aco_pointer": "arifle_Katiba_C_ACO_pointer_F",
      "c_aco_pointer_snds": "arifle_Katiba_C_ACO_pointer_snds_F",
      "c": "arifle_Katiba_C_F",
      "gl_aco": "arifle_Katiba_GL_ACO_F",
      "gl_aco_pointer": "arifle_Katiba_GL_ACO_pointer_F",
      "gl_aco_pointer_snds": "arifle_Katiba_GL_ACO_pointer_snds_F",
      "gl_arco_pointer": "arifle_Katiba_GL_ARCO_pointer_F",
      "gl": "arifle_Katiba_GL_F",
      "gl_nstalker_pointer": "arifle_Katiba_GL_Nstalker_pointer_F",
      "pointer": "arifle_Katiba_pointer_F",
    }),
    "mk20": cfgNode("arifle_Mk20_F", {
      "aco": "arifle_Mk20_ACO_F",
      "aco_pointer": "arifle_Mk20_ACO_pointer_F",
      "gl_aco": "arifle_Mk20_GL_ACO_F",
      "gl": "arifle_Mk20_GL_F",
      "gl_mrco_pointer": "arifle_Mk20_GL_MRCO_pointer_F",
      "gl_plain": "arifle_Mk20_GL_plain_F",
      "holo": "arifle_Mk20_Holo_F",
      "mrco": "arifle_Mk20_MRCO_F",
      "mrco_plain": "arifle_Mk20_MRCO_plain_F",
      "mrco_pointer": "arifle_Mk20_MRCO_pointer_F",
      "plain": "arifle_Mk20_plain_F",
      "pointer": "arifle_Mk20_pointer_F",
    }),
    "mk20c": cfgNode("arifle_Mk20C_F", {
      "aco": "arifle_Mk20C_ACO_F",
      "aco_pointer": "arifle_Mk20C_ACO_pointer_F",
      "plain": "arifle_Mk20C_plain_F",
    }),
    "msbs65": cfgNode("arifle_MSBS65_F", {
      "aco": "arifle_MSBS65_aco_F",
      "black_aco": "arifle_MSBS65_black_aco_F",
      "black_aco_fl": "arifle_MSBS65_black_aco_FL_F",
      "black": "arifle_MSBS65_black_F",
      "black_ico": "arifle_MSBS65_black_ico_F",
      "black_ico_pointer_f": "arifle_MSBS65_black_ico_pointer_f",
      "camo": "arifle_MSBS65_camo_F",
      "gl_black": "arifle_MSBS65_GL_black_F",
      "gl_black_ico": "arifle_MSBS65_GL_black_ico_F",
      "gl_black_ico_pointer_f": "arifle_MSBS65_GL_black_ico_pointer_f",
      "gl_camo": "arifle_MSBS65_GL_camo_F",
      "gl": "arifle_MSBS65_GL_F",
      "gl_ico": "arifle_MSBS65_GL_ico_F",
      "gl_ico_pointer_f": "arifle_MSBS65_GL_ico_pointer_f",
      "gl_sand": "arifle_MSBS65_GL_sand_F",
      "ico": "arifle_MSBS65_ico_F",
      "ico_pointer_f": "arifle_MSBS65_ico_pointer_f",
      "mark_black": "arifle_MSBS65_Mark_black_F",
      "mark_camo": "arifle_MSBS65_Mark_camo_F",
      "mark": "arifle_MSBS65_Mark_F",
      "mark_sand": "arifle_MSBS65_Mark_sand_F",
      "mark_sos_lp_bi": "arifle_MSBS65_Mark_SOS_LP_BI_F",
      "sand": "arifle_MSBS65_sand_F",
      "ubs_black": "arifle_MSBS65_UBS_black_F",
      "ubs_black_ico": "arifle_MSBS65_UBS_black_ico_F",
      "ubs_black_ico_pointer_f": "arifle_MSBS65_UBS_black_ico_pointer_f",
      "ubs_camo": "arifle_MSBS65_UBS_camo_F",
      "ubs": "arifle_MSBS65_UBS_F",
      "ubs_ico": "arifle_MSBS65_UBS_ico_F",
      "ubs_ico_pointer_f": "arifle_MSBS65_UBS_ico_pointer_f",
      "ubs_sand": "arifle_MSBS65_UBS_sand_F",
      "ubs_snds_ico_pointer": "arifle_MSBS65_UBS_snds_ico_pointer_F",
    }),
    "mx": cfgNode("arifle_MX_F", {
      "aco": "arifle_MX_ACO_F",
      "aco_pointer": "arifle_MX_ACO_pointer_F",
      "aco_pointer_snds": "arifle_MX_ACO_pointer_snds_F",
      "black_aco_fl": "arifle_MX_Black_ACO_FL_F",
      "black_aco_pointer": "arifle_MX_Black_ACO_Pointer_F",
      "black_aco_pointer_snds": "arifle_MX_Black_ACO_Pointer_Snds_F",
      "black": "arifle_MX_Black_F",
      "black_hamr_pointer": "arifle_MX_Black_Hamr_pointer_F",
      "black_hamr_pointer_snds": "arifle_MX_Black_Hamr_Pointer_Snds_F",
      "black_holo_pointer": "arifle_MX_Black_Holo_Pointer_F",
      "black_pointer": "arifle_MX_Black_Pointer_F",
      "gl_aco": "arifle_MX_GL_ACO_F",
      "gl_aco_pointer": "arifle_MX_GL_ACO_pointer_F",
      "gl_black_aco": "arifle_MX_GL_Black_ACO_F",
      "gl_black": "arifle_MX_GL_Black_F",
      "gl_black_hamr_pointer": "arifle_MX_GL_Black_Hamr_pointer_F",
      "gl_black_holo_pointer_snds": "arifle_MX_GL_Black_Holo_Pointer_Snds_F",
      "gl": "arifle_MX_GL_F",
      "gl_hamr_pointer": "arifle_MX_GL_Hamr_pointer_F",
      "gl_holo_pointer_snds": "arifle_MX_GL_Holo_pointer_snds_F",
      "gl_khk_aco": "arifle_MX_GL_khk_ACO_F",
      "gl_khk": "arifle_MX_GL_khk_F",
      "gl_khk_hamr_pointer": "arifle_MX_GL_khk_Hamr_Pointer_F",
      "gl_khk_holo_pointer_snds": "arifle_MX_GL_khk_Holo_Pointer_Snds_F",
      "hamr_pointer": "arifle_MX_Hamr_pointer_F",
      "holo_pointer": "arifle_MX_Holo_pointer_F",
      "khk_aco_pointer": "arifle_MX_khk_ACO_Pointer_F",
      "khk_aco_pointer_snds": "arifle_MX_khk_ACO_Pointer_Snds_F",
      "khk": "arifle_MX_khk_F",
      "khk_hamr_pointer": "arifle_MX_khk_Hamr_Pointer_F",
      "khk_hamr_pointer_snds": "arifle_MX_khk_Hamr_Pointer_Snds_F",
      "khk_holo_pointer": "arifle_MX_khk_Holo_Pointer_F",
      "khk_pointer": "arifle_MX_khk_Pointer_F",
      "pointer": "arifle_MX_pointer_F",
      "rco_pointer_snds": "arifle_MX_RCO_pointer_snds_F",
      "sw_black": "arifle_MX_SW_Black_F",
      "sw_black_hamr_pointer": "arifle_MX_SW_Black_Hamr_pointer_F",
      "sw_black_pointer": "arifle_MX_SW_Black_Pointer_F",
      "sw": "arifle_MX_SW_F",
      "sw_hamr_pointer": "arifle_MX_SW_Hamr_pointer_F",
      "sw_khk": "arifle_MX_SW_khk_F",
      "sw_khk_pointer": "arifle_MX_SW_khk_Pointer_F",
      "sw_pointer": "arifle_MX_SW_pointer_F",
    }),
    "mxc": cfgNode("arifle_MXC_F", {
      "aco": "arifle_MXC_ACO_F",
      "aco_pointer": "arifle_MXC_ACO_pointer_F",
      "aco_pointer_snds": "arifle_MXC_ACO_pointer_snds_F",
      "black_aco": "arifle_MXC_Black_ACO_F",
      "black_aco_pointer_snds": "arifle_MXC_Black_ACO_Pointer_Snds_F",
      "black": "arifle_MXC_Black_F",
      "black_holo_fl": "arifle_MXC_Black_Holo_FL_F",
      "black_holo_pointer": "arifle_MXC_Black_Holo_Pointer_F",
      "holo": "arifle_MXC_Holo_F",
      "holo_pointer": "arifle_MXC_Holo_pointer_F",
      "holo_pointer_snds": "arifle_MXC_Holo_pointer_snds_F",
      "khk_aco": "arifle_MXC_khk_ACO_F",
      "khk_aco_pointer_snds": "arifle_MXC_khk_ACO_Pointer_Snds_F",
      "khk": "arifle_MXC_khk_F",
      "khk_holo_pointer": "arifle_MXC_khk_Holo_Pointer_F",
      "sos_point_snds": "arifle_MXC_SOS_point_snds_F",
    }),
    "mxm": cfgNode("arifle_MXM_F", {
      "black": "arifle_MXM_Black_F",
      "black_mos_pointer_bipod": "arifle_MXM_Black_MOS_Pointer_Bipod_F",
      "black_mos_pointer_bipod_snds": "arifle_MXM_Black_MOS_Pointer_Bipod_Snds_F",
      "dms": "arifle_MXM_DMS_F",
      "dms_lp_bi_snds": "arifle_MXM_DMS_LP_BI_snds_F",
      "hamr_lp_bi": "arifle_MXM_Hamr_LP_BI_F",
      "hamr_pointer": "arifle_MXM_Hamr_pointer_F",
      "khk": "arifle_MXM_khk_F",
      "khk_mos_pointer_bipod": "arifle_MXM_khk_MOS_Pointer_Bipod_F",
      "khk_mos_pointer_bipod_snds": "arifle_MXM_khk_MOS_Pointer_Bipod_Snds_F",
      "rco_pointer_snds": "arifle_MXM_RCO_pointer_snds_F",
      "sos_pointer": "arifle_MXM_SOS_pointer_F",
    }),
    "rpk12": cfgNode("arifle_RPK12_F", {
      "arid": "arifle_RPK12_arid_F",
      "lush_arco_pointer": "arifle_RPK12_lush_arco_pointer_F",
      "lush_arco_snds_pointer": "arifle_RPK12_lush_arco_snds_pointer_F",
      "lush": "arifle_RPK12_lush_F",
      "lush_holo_snds_pointer": "arifle_RPK12_lush_holo_snds_pointer_F",
    }),
    "sdar": cfgNode("arifle_SDAR_F", {}),
    "spar": {
      "01_blk_aco_pointer": "arifle_SPAR_01_blk_ACO_Pointer_F",
      "01_blk_erco_pointer": "arifle_SPAR_01_blk_ERCO_Pointer_F",
      "01_blk": "arifle_SPAR_01_blk_F",
      "01_gl_blk_aco_pointer": "arifle_SPAR_01_GL_blk_ACO_Pointer_F",
      "01_gl_blk_erco_pointer": "arifle_SPAR_01_GL_blk_ERCO_Pointer_F",
      "01_gl_blk": "arifle_SPAR_01_GL_blk_F",
      "01_gl_khk": "arifle_SPAR_01_GL_khk_F",
      "01_gl_snd": "arifle_SPAR_01_GL_snd_F",
      "01_khk": "arifle_SPAR_01_khk_F",
      "01_snd": "arifle_SPAR_01_snd_F",
      "02_blk_erco_pointer": "arifle_SPAR_02_blk_ERCO_Pointer_F",
      "02_blk": "arifle_SPAR_02_blk_F",
      "02_blk_pointer": "arifle_SPAR_02_blk_Pointer_F",
      "02_khk": "arifle_SPAR_02_khk_F",
      "02_snd": "arifle_SPAR_02_snd_F",
      "03_blk": "arifle_SPAR_03_blk_F",
      "03_blk_mos_pointer_bipod": "arifle_SPAR_03_blk_MOS_Pointer_Bipod_F",
      "03_khk": "arifle_SPAR_03_khk_F",
      "03_snd": "arifle_SPAR_03_snd_F",
    },
    "trg20": cfgNode("arifle_TRG20_F", {
      "aco": "arifle_TRG20_ACO_F",
      "aco_flash": "arifle_TRG20_ACO_Flash_F",
      "aco_pointer": "arifle_TRG20_ACO_pointer_F",
      "holo": "arifle_TRG20_Holo_F",
    }),
    "trg21": cfgNode("arifle_TRG21_F", {
      "aco_pointer": "arifle_TRG21_ACO_pointer_F",
      "arco_pointer": "arifle_TRG21_ARCO_pointer_F",
      "gl_aco_pointer": "arifle_TRG21_GL_ACO_pointer_F",
      "gl": "arifle_TRG21_GL_F",
      "gl_mrco": "arifle_TRG21_GL_MRCO_F",
      "mrco": "arifle_TRG21_MRCO_F",
    }),
  },
  "B": {
    "patrol": {
      "soldier_autorifleman_weapon": "B_Patrol_Soldier_Autorifleman_weapon_F",
      "soldier_carrier_weapon": "B_Patrol_Soldier_Carrier_weapon_F",
      "soldier_heavygunner_weapon": "B_Patrol_Soldier_HeavyGunner_weapon_F",
      "soldier_leader_weapon": "B_Patrol_Soldier_Leader_weapon_F",
      "soldier_machinegunner_weapon": "B_Patrol_Soldier_MachineGunner_weapon_F",
      "soldier_marksman_weapon": "B_Patrol_Soldier_Marksman_weapon_F",
      "soldier_medic_weapon": "B_Patrol_Soldier_Medic_weapon_F",
      "soldier_operator_weapon": "B_Patrol_Soldier_Operator_weapon_F",
      "soldier_pistol": "B_Patrol_Soldier_Pistol_F",
      "soldier_specialist_weapon": "B_Patrol_Soldier_Specialist_weapon_F",
    },
  },
  "FakeWeapon": {
    "moduletracers": cfgNode("FakeWeapon_moduleTracers_F", {}),
  },
  "hgun": {
    "acpc2": cfgNode("hgun_ACPC2_F", {
      "snds": "hgun_ACPC2_snds_F",
    }),
    "esd": {
      "01_antenna_01": "hgun_esd_01_antenna_01_F",
      "01_antenna_02": "hgun_esd_01_antenna_02_F",
      "01_antenna_03": "hgun_esd_01_antenna_03_F",
      "01_base": "hgun_esd_01_base_F",
      "01_dummy": "hgun_esd_01_dummy_F",
      "01": "hgun_esd_01_F",
    },
    "p07": cfgNode("hgun_P07_F", {
      "blk": "hgun_P07_blk_F",
      "blk_snds": "hgun_P07_blk_Snds_F",
      "khk": "hgun_P07_khk_F",
      "khk_snds": "hgun_P07_khk_Snds_F",
      "snds": "hgun_P07_snds_F",
    }),
    "pdw2000": cfgNode("hgun_PDW2000_F", {
      "holo": "hgun_PDW2000_Holo_F",
      "holo_snds": "hgun_PDW2000_Holo_snds_F",
      "snds": "hgun_PDW2000_snds_F",
    }),
    "pistol": {
      "01": "hgun_Pistol_01_F",
      "heavy_01": "hgun_Pistol_heavy_01_F",
      "heavy_01_green": "hgun_Pistol_heavy_01_green_F",
      "heavy_01_green_snds": "hgun_Pistol_heavy_01_green_snds_F",
      "heavy_01_mrd": "hgun_Pistol_heavy_01_MRD_F",
      "heavy_01_snds": "hgun_Pistol_heavy_01_snds_F",
      "heavy_02": "hgun_Pistol_heavy_02_F",
      "heavy_02_yorris": "hgun_Pistol_heavy_02_Yorris_F",
      "signal": "hgun_Pistol_Signal_F",
    },
    "rook40": cfgNode("hgun_Rook40_F", {
      "snds": "hgun_Rook40_snds_F",
    }),
  },
  "HMG": {
    "m2": {
      "mounted": "HMG_M2_Mounted",
    },
  },
  "launch": {
    "b": {
      "titan": "launch_B_Titan_F",
      "titan_olive": "launch_B_Titan_olive_F",
      "titan_short": "launch_B_Titan_short_F",
      "titan_short_tna": "launch_B_Titan_short_tna_F",
      "titan_tna": "launch_B_Titan_tna_F",
    },
    "i": {
      "titan_eaf": "launch_I_Titan_eaf_F",
      "titan": "launch_I_Titan_F",
      "titan_short": "launch_I_Titan_short_F",
    },
    "mraws": {
      "green": "launch_MRAWS_green_F",
      "green_rail": "launch_MRAWS_green_rail_F",
      "olive": "launch_MRAWS_olive_F",
      "olive_rail": "launch_MRAWS_olive_rail_F",
      "sand": "launch_MRAWS_sand_F",
      "sand_rail": "launch_MRAWS_sand_rail_F",
    },
    "nlaw": cfgNode("launch_NLAW_F", {}),
    "o": {
      "titan": "launch_O_Titan_F",
      "titan_ghex": "launch_O_Titan_ghex_F",
      "titan_short": "launch_O_Titan_short_F",
      "titan_short_ghex": "launch_O_Titan_short_ghex_F",
      "vorona_brown": "launch_O_Vorona_brown_F",
      "vorona_green": "launch_O_Vorona_green_F",
    },
    "rpg32": cfgNode("launch_RPG32_F", {
      "camo": "launch_RPG32_camo_F",
      "ghex": "launch_RPG32_ghex_F",
      "green": "launch_RPG32_green_F",
    }),
    "rpg7": cfgNode("launch_RPG7_F", {}),
    "titan": cfgNode("launch_Titan_F", {
      "short": "launch_Titan_short_F",
    }),
  },
  "LMG": {
    "03": cfgNode("LMG_03_F", {
      "vehicle": "LMG_03_Vehicle_F",
    }),
    "mk200": cfgNode("LMG_Mk200_F", {
      "bi": "LMG_Mk200_BI_F",
      "black_aco_pointer": "LMG_Mk200_black_ACO_pointer_F",
      "black_bi": "LMG_Mk200_black_BI_F",
      "black": "LMG_Mk200_black_F",
      "black_lp_bi": "LMG_Mk200_black_LP_BI_F",
      "lp_bi": "LMG_Mk200_LP_BI_F",
      "mrco": "LMG_Mk200_MRCO_F",
      "pointer": "LMG_Mk200_pointer_F",
    }),
    "zafir": cfgNode("LMG_Zafir_F", {
      "arco": "LMG_Zafir_ARCO_F",
      "pointer": "LMG_Zafir_pointer_F",
    }),
  },
  "MMG": {
    "01": {
      "hex_arco_lp": "MMG_01_hex_ARCO_LP_F",
      "hex": "MMG_01_hex_F",
      "tan": "MMG_01_tan_F",
    },
    "02": {
      "black": "MMG_02_black_F",
      "black_rco_bi": "MMG_02_black_RCO_BI_F",
      "camo": "MMG_02_camo_F",
      "sand": "MMG_02_sand_F",
      "sand_rco_lp": "MMG_02_sand_RCO_LP_F",
    },
  },
  "sgun": {
    "huntershotgun": {
      "01": "sgun_HunterShotgun_01_F",
      "01_sawedoff": "sgun_HunterShotgun_01_sawedoff_F",
    },
  },
  "SMG": {
    "01": cfgNode("SMG_01_F", {
      "aco": "SMG_01_ACO_F",
      "holo": "SMG_01_Holo_F",
      "holo_pointer_snds": "SMG_01_Holo_pointer_snds_F",
    }),
    "02": cfgNode("SMG_02_F", {
      "aco": "SMG_02_ACO_F",
      "arco_pointg": "SMG_02_ARCO_pointg_F",
      "flash": "SMG_02_flash_F",
    }),
    "03": {
      "black": "SMG_03_black",
      "camo": "SMG_03_camo",
      "hex": "SMG_03_hex",
      "khaki": "SMG_03_khaki",
      "tr_black": "SMG_03_TR_black",
      "tr_camo": "SMG_03_TR_camo",
      "tr_hex": "SMG_03_TR_hex",
      "tr_khaki": "SMG_03_TR_khaki",
    },
    "03c": {
      "black": "SMG_03C_black",
      "camo": "SMG_03C_camo",
      "hex": "SMG_03C_hex",
      "khaki": "SMG_03C_khaki",
      "tr_black": "SMG_03C_TR_black",
      "tr_camo": "SMG_03C_TR_camo",
      "tr_hex": "SMG_03C_TR_hex",
      "tr_khaki": "SMG_03C_TR_khaki",
    },
    "05": cfgNode("SMG_05_F", {}),
  },
  "srifle": {
    "dmr": {
      "01_aco": "srifle_DMR_01_ACO_F",
      "01_arco": "srifle_DMR_01_ARCO_F",
      "01_dms_bi": "srifle_DMR_01_DMS_BI_F",
      "01_dms": "srifle_DMR_01_DMS_F",
      "01_dms_snds_bi": "srifle_DMR_01_DMS_snds_BI_F",
      "01_dms_snds": "srifle_DMR_01_DMS_snds_F",
      "01": "srifle_DMR_01_F",
      "01_mrco": "srifle_DMR_01_MRCO_F",
      "01_sos": "srifle_DMR_01_SOS_F",
      "02_aco": "srifle_DMR_02_ACO_F",
      "02_arco": "srifle_DMR_02_ARCO_F",
      "02_camo_ams_lp": "srifle_DMR_02_camo_AMS_LP_F",
      "02_camo": "srifle_DMR_02_camo_F",
      "02_dms": "srifle_DMR_02_DMS_F",
      "02": "srifle_DMR_02_F",
      "02_mrco": "srifle_DMR_02_MRCO_F",
      "02_sniper_ams_lp_s": "srifle_DMR_02_sniper_AMS_LP_S_F",
      "02_sniper": "srifle_DMR_02_sniper_F",
      "02_sos": "srifle_DMR_02_SOS_F",
      "03_aco": "srifle_DMR_03_ACO_F",
      "03_ams": "srifle_DMR_03_AMS_F",
      "03_arco": "srifle_DMR_03_ARCO_F",
      "03_dms": "srifle_DMR_03_DMS_F",
      "03_dms_snds": "srifle_DMR_03_DMS_snds_F",
      "03": "srifle_DMR_03_F",
      "03_khaki": "srifle_DMR_03_khaki_F",
      "03_mrco": "srifle_DMR_03_MRCO_F",
      "03_multicam": "srifle_DMR_03_multicam_F",
      "03_sos": "srifle_DMR_03_SOS_F",
      "03_tan_ams_lp": "srifle_DMR_03_tan_AMS_LP_F",
      "03_tan": "srifle_DMR_03_tan_F",
      "03_woodland": "srifle_DMR_03_woodland_F",
      "04_aco": "srifle_DMR_04_ACO_F",
      "04_arco": "srifle_DMR_04_ARCO_F",
      "04_dms": "srifle_DMR_04_DMS_F",
      "04_dms_weathered_kir_f": "srifle_DMR_04_DMS_weathered_Kir_F_F",
      "04": "srifle_DMR_04_F",
      "04_mrco": "srifle_DMR_04_MRCO_F",
      "04_ns_lp": "srifle_DMR_04_NS_LP_F",
      "04_sos": "srifle_DMR_04_SOS_F",
      "04_tan": "srifle_DMR_04_Tan_F",
      "05_aco": "srifle_DMR_05_ACO_F",
      "05_arco": "srifle_DMR_05_ARCO_F",
      "05_blk": "srifle_DMR_05_blk_F",
      "05_dms": "srifle_DMR_05_DMS_F",
      "05_dms_snds": "srifle_DMR_05_DMS_snds_F",
      "05_hex": "srifle_DMR_05_hex_F",
      "05_khs_lp": "srifle_DMR_05_KHS_LP_F",
      "05_mrco": "srifle_DMR_05_MRCO_F",
      "05_sos": "srifle_DMR_05_SOS_F",
      "05_tan_f": "srifle_DMR_05_tan_f",
      "06_camo": "srifle_DMR_06_camo_F",
      "06_camo_khs": "srifle_DMR_06_camo_khs_F",
      "06_hunter": "srifle_DMR_06_hunter_F",
      "06_hunter_khs": "srifle_DMR_06_hunter_khs_F",
      "06_olive": "srifle_DMR_06_olive_F",
      "07_blk_dms": "srifle_DMR_07_blk_DMS_F",
      "07_blk_dms_snds": "srifle_DMR_07_blk_DMS_Snds_F",
      "07_blk": "srifle_DMR_07_blk_F",
      "07_blk_f_arco_flash": "srifle_DMR_07_blk_F_arco_flash_F",
      "07_ghex": "srifle_DMR_07_ghex_F",
      "07_hex": "srifle_DMR_07_hex_F",
    },
    "ebr": cfgNode("srifle_EBR_F", {
      "aco": "srifle_EBR_ACO_F",
      "arco_pointer": "srifle_EBR_ARCO_pointer_F",
      "arco_pointer_snds": "srifle_EBR_ARCO_pointer_snds_F",
      "dms": "srifle_EBR_DMS_F",
      "dms_pointer_snds": "srifle_EBR_DMS_pointer_snds_F",
      "hamr_pointer": "srifle_EBR_Hamr_pointer_F",
      "mrco_lp_bi": "srifle_EBR_MRCO_LP_BI_F",
      "mrco_pointer": "srifle_EBR_MRCO_pointer_F",
      "sos": "srifle_EBR_SOS_F",
    }),
    "gm6": cfgNode("srifle_GM6_F", {
      "camo": "srifle_GM6_camo_F",
      "camo_lrps": "srifle_GM6_camo_LRPS_F",
      "camo_sos": "srifle_GM6_camo_SOS_F",
      "ghex": "srifle_GM6_ghex_F",
      "ghex_lrps": "srifle_GM6_ghex_LRPS_F",
      "lrps": "srifle_GM6_LRPS_F",
      "sos": "srifle_GM6_SOS_F",
    }),
    "lrr": cfgNode("srifle_LRR_F", {
      "camo": "srifle_LRR_camo_F",
      "camo_lrps": "srifle_LRR_camo_LRPS_F",
      "camo_sos": "srifle_LRR_camo_SOS_F",
      "lrps": "srifle_LRR_LRPS_F",
      "sos": "srifle_LRR_SOS_F",
      "tna": "srifle_LRR_tna_F",
      "tna_lrps": "srifle_LRR_tna_LRPS_F",
    }),
  },
} as const satisfies CfgTree;

export type CfgWeapons = typeof cfgWeapons;

export const weaponsList = {
  cfgWeapons,
} as const;
