import { mkdir } from "node:fs/promises";
import { join } from "node:path";

const GENERATED_PATHS_FILE = join("lance_modules", "tsconfig.paths.json");

export async function writeGeneratedTsconfigPaths(
	cwd: string,
	dependencies: Record<string, unknown>,
): Promise<void> {
	const outPath = join(cwd, GENERATED_PATHS_FILE);
	await mkdir(join(cwd, "lance_modules"), { recursive: true });

	const paths: Record<string, string[]> = {};
	for (const name of Object.keys(dependencies).sort()) {
		paths[name] = [`./../lance_modules/${name}/index`];
		paths[`${name}/*`] = [`./../lance_modules/${name}/*`];
	}

	const content = [
		"{",
		'  // WARNING: This file is auto generated by Lance CLI.',
		'  // Do not edit manually; your changes may be overwritten.',
		'  "compilerOptions": {',
		'    "paths": {',
		...renderPaths(paths),
		"    }",
		"  }",
		"}",
		"",
	].join("\n");

	await Bun.write(outPath, content);
}

function renderPaths(paths: Record<string, string[]>): string[] {
	const entries = Object.entries(paths);
	if (entries.length === 0) return [];
	return entries.map(([k, v], i) => {
		const isLast = i === entries.length - 1;
		return `      ${JSON.stringify(k)}: ${JSON.stringify(v)}${isLast ? "" : ","}`;
	});
}
